apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: backstage
  name: backstage
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/apicurio/backstage:latest
    importPolicy:
      scheduled: true
    name: latest
