- op: replace
  path: "/spec/template/spec/containers/0/resources"
  value:
    limits:
      cpu: 400m
      memory: 1000Mi
    requests:
      cpu: 200m
      memory: 600Mi
- op: add
  path: "/spec/template/spec/containers/-"
  value: 
    name: tenant-manager
    image: quay.io/apicurio/apicurio-registry-tenant-manager-api:latest-snapshot
    imagePullPolicy: Always
    ports:
      - containerPort: 8585
        protocol: TCP
    env:
      - name: DATASOURCE_URL
        valueFrom:
          configMapKeyRef:
            name: postgresql-tenantmanager-configmap
            key: pg-ds-url
      - name: DATASOURCE_USERNAME
        valueFrom:
          configMapKeyRef:
            name: postgresql-tenantmanager-configmap
            key: pg-user
      - name: DATASOURCE_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: postgresql-tenantmanager-configmap
            key: pg-pwd

      - name: REGISTRY_ROUTE_URL
        value: http://localhost:8080

      - name: QUARKUS_HTTP_PORT
        value: "8585"
      - name: TENANT_MANAGER_LOG_LEVEL
        value: DEBUG
    resources:
      limits:
        cpu: 200m
        memory: 800Mi
      requests:
        cpu: 100m
        memory: 600Mi
    livenessProbe:
      httpGet:
        path: /health/live
        port: 8585
        scheme: HTTP
      initialDelaySeconds: 5
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /health/ready
        port: 8585
        scheme: HTTP
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 5
    terminationMessagePath: /dev/termination-log
- op: add
  path: "/spec/template/spec/containers/-"
  value: 
    name: envoy
    image: envoyproxy/envoy:v1.18.3
    command: ["envoy"]
    args: ["-c", "/etc/envoy.yaml", "--service-node", "apicurio", "--service-cluster", "apicurio", "-l", "debug"]
    ports:
      - name: envoy-http
        containerPort: 38080
        protocol: TCP
      - name: envoy-metrics
        containerPort: 9901
        protocol: TCP
    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 150m
        memory: 300Mi
    volumeMounts:
    - name: apicurio-envoy-config
      mountPath: /etc/envoy.yaml
      subPath: envoy.yaml
- op: add
  path: /spec/template/spec/volumes
  value: 
    - name: apicurio-envoy-config
      configMap:
        name: apicurio-envoy-config
