- op: replace
  path: "/spec/template/spec/containers/0/resources"
  value:
    limits:
      cpu: 300m
      memory: 600Mi
    requests:
      cpu: 300m
      memory: 600Mi
- op: add
  path: "/spec/template/spec/containers/-"
  value: 
    name: tenant-manager
    image: tenant-manager:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 8585
        protocol: TCP
    env:
      - name: DATASOURCE_URL
        valueFrom:
          configMapKeyRef:
            name: postgresql-tenantmanager-configmap-mt
            key: pg-ds-url
      - name: DATASOURCE_USERNAME
        valueFrom:
          configMapKeyRef:
            name: postgresql-tenantmanager-configmap-mt
            key: pg-user
      - name: DATASOURCE_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: postgresql-tenantmanager-configmap-mt
            key: pg-pwd

      - name: REGISTRY_ROUTE_URL
        value: http://localhost:8080

      - name: QUARKUS_HTTP_PORT
        value: "8585"
      - name: TENANT_MANAGER_LOG_LEVEL
        value: DEBUG

      - name: AUTH_ENABLED
        value: "true"
      - name: KEYCLOAK_URL
        value: "https://auth.apicur.io/auth"
      - name: KEYCLOAK_REALM
        value: "operate-first-apicurio"
      - name: KEYCLOAK_API_CLIENT_ID
        value: "sr-tenant-manager"
    resources:
      limits:
        cpu: 300m
        memory: 600Mi
      requests:
        cpu: 300m
        memory: 600Mi
    livenessProbe:
      httpGet:
        path: /q/health/live
        port: 8585
        scheme: HTTP
      initialDelaySeconds: 30
      timeoutSeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 5
    readinessProbe:
      httpGet:
        path: /q/health/ready
        port: 8585
        scheme: HTTP
      initialDelaySeconds: 30
      timeoutSeconds: 10
      periodSeconds: 15
      successThreshold: 1
      failureThreshold: 8
    terminationMessagePath: /dev/termination-log
- op: add
  path: "/spec/template/spec/containers/-"
  value: 
    name: envoy
    image: envoyproxy/envoy:v1.18.3
    command: ["envoy"]
    args: ["-c", "/etc/envoy.yaml", "--service-node", "apicurio", "--service-cluster", "apicurio", "-l", "debug"]
    ports:
      - name: envoy-http
        containerPort: 38080
        protocol: TCP
      - name: envoy-metrics
        containerPort: 9901
        protocol: TCP
    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 200m
        memory: 300Mi
    volumeMounts:
    - name: apicurio-envoy-config
      mountPath: /etc/envoy.yaml
      subPath: envoy.yaml
- op: add
  path: /spec/template/spec/volumes
  value: 
    - name: apicurio-envoy-config
      configMap:
        name: apicurio-envoy-config-mt
- op: replace
  path: /spec/triggers
  value:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - apicurio-registry
        from:
          kind: ImageStreamTag
          name: apicurio-registry-mt:latest
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - tenant-manager
        from:
          kind: ImageStreamTag
          name: tenant-manager-mt:latest
      type: ImageChange
