apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gchat-webhook-external-secret
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: gchat-webhook
  dataFrom:
    - extract:
        key: moc/smaug/apicurio-apicurio-registry/gchat-webhook