apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gchat-webhook-ext-secret
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: gchat-webhook
  dataFrom:
    - extract:
        key: moc/smaug/apicurio-apicurio-registry/gchat-webhook

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-ext-secret
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: tenant-manager-auth-secret
  dataFrom:
    - extract:
        key: moc/smaug/apicurio-apicurio-registry/sso

