kind: ConfigMap
apiVersion: v1
metadata:
  name: registry-deployments-config-file
  labels:
    app: fleet-manager
data:
  registry-deployments.yaml: |-
    deployments:
      - name: default
        # Route to registry
        registryDeploymentUrl: https://apicurio-registry-mt-apicurio-apicurio-registry.apps.smaug.na.operate-first.cloud/
        # Path to tenant manager service
        tenantManagerUrl: http://tenant-manager-mt:8585 

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: registry-quota-plans-config
  labels:
    app: fleet-manager
data:
  quota-plans.yaml: |-
    reconcile: false # Enable this if you make changes to the plans configuration
    plans:
      - name: default
        resources:
          - type: MAX_TOTAL_SCHEMAS_COUNT
            limit: 1000
          - type: MAX_SCHEMA_SIZE_BYTES
            limit: 65536 # 64 KiB
          - type: MAX_ARTIFACTS_COUNT
            limit: -1
          - type: MAX_VERSIONS_PER_ARTIFACT_COUNT
            limit: -1
          - type: MAX_ARTIFACT_PROPERTIES_COUNT
            limit: 50
          - type: MAX_PROPERTY_KEY_SIZE_BYTES
            limit: 256
          - type: MAX_PROPERTY_VALUE_SIZE_BYTES
            limit: 1024
          - type: MAX_ARTIFACT_LABELS_COUNT
            limit: 50
          - type: MAX_LABEL_SIZE_BYTES
            limit: 256
          - type: MAX_ARTIFACT_NAME_LENGTH_CHARS
            limit: -1
          - type: MAX_ARTIFACT_DESCRIPTION_LENGTH_CHARS
            limit: -1
          - type: MAX_REQUESTS_PER_SECOND_COUNT
            limit: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-manager
  labels:
    app: fleet-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-manager
  template:
    metadata:
      labels:
        app: fleet-manager
    spec:
      volumes:
        - name: registry-deployments-config-file
          configMap:
            name: registry-deployments-config-file
        - name: registry-quota-plans-config
          configMap:
            name: registry-quota-plans-config
      containers:
        - name: fleet-manager
          image: quay.io/apicurio/apicurio-registry-fleet-manager-api:latest-snapshot
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          env:
            - name: SERVICE_API_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: postgresql-fleetmanager-configmap
                  key: pg-ds-url
            - name: SERVICE_API_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgresql-fleetmanager-configmap
                  key: pg-user
            - name: SERVICE_API_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgresql-fleetmanager-configmap
                  key: pg-pwd
            - name: REGISTRY_BROWSER_URL
              value: 'https://apicurio-registry-mt-apicurio-apicurio-registry.apps.smaug.na.operate-first.cloud/t/TENANT_ID'
            - name: REGISTRY_QUOTA_PLANS_CONFIG_FILE
              value: '/config/quota-plans.yaml'
            - name: REGISTRY_DEPLOYMENTS_CONFIG_FILE
              value: '/config/registry-deployments.yaml'
          volumeMounts:
            - name: registry-deployments-config-file
              mountPath: /config/registry-deployments.yaml
              subPath: registry-deployments.yaml
            - name: registry-quota-plans-config
              mountPath: /config/quota-plans.yaml
              subPath: quota-plans.yaml
          resources:
            limits:
              cpu: 500m
              memory: 1300Mi
            requests:
              cpu: 300m
              memory: 600Mi
          terminationMessagePath: /dev/termination-log
  strategy:
    type: Recreate

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fleet-manager
  name: fleet-manager
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: fleet-manager
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fleet-manager
  labels:
    app: fleet-manager
spec:
  to:
    kind: Service
    #HEY workaround here!! because of using nameSuffix: '-mt' in Kustomize
    name: fleet-manager-mt
    weight: 100
  wildcardPolicy: None