apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-manager
  labels:
    app: fleet-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-manager
  template:
    metadata:
      labels:
        app: fleet-manager
    spec:
      containers:
        - name: fleet-manager
          image: quay.io/apicurio/apicurio-registry-fleet-manager-api:latest-snapshot
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          env:
            - name: SERVICE_API_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: postgresql-fleetmanager-configmap
                  key: pg-ds-url
            - name: SERVICE_API_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgresql-fleetmanager-configmap
                  key: pg-user
            - name: SERVICE_API_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgresql-fleetmanager-configmap
                  key: pg-pwd
          resources:
            limits:
              cpu: 500m
              memory: 1300Mi
            requests:
              cpu: 300m
              memory: 600Mi
          terminationMessagePath: /dev/termination-log
  strategy:
    type: Recreate

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fleet-manager
  name: fleet-manager
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: fleet-manager
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fleet-manager
  labels:
    app: fleet-manager
spec:
  to:
    kind: Service
    #HEY workaround here!! because of using nameSuffix: '-mt' in Kustomize
    name: fleet-manager-mt
    weight: 100
  wildcardPolicy: None