apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apicurio-registry-mt-ui
  name: apicurio-registry-mt-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-registry-mt-ui
  template:
    metadata:
      labels:
        app: apicurio-registry-mt-ui
    spec:
      containers:
        - name: apicurio-registry-mt-ui
          image: quay.io/apicurio/apicurio-registry-mt-ui:latest
          env:
            - name: TENANT_MANAGER_API
              # TODO find away to get this values dynamically, instead of setting this cluster url manually
              value: https://tenant-manager-mt-apicurio-apicurio-registry.apps.smaug.na.operate-first.cloud/api/v1
              # value: http://tenant-manager.127.0.0.1.nip.io/api/v1
            - name: MT_REGISTRY_APIS
              value: https://apicurio-envoy-mt-apicurio-apicurio-registry.apps.smaug.na.operate-first.cloud/t/:tenantId/apis
              # value: http://apicurio-envoy.127.0.0.1.nip.io/t/:tenantId/apis
          ports:
            - containerPort: 8080
              protocol: TCP
          # readinessProbe:
          #   tcpSocket:
          #     port: 5432
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   tcpSocket:
          #     port: 5432
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
          resources:
            limits:
              cpu: 250m
              memory: 875Mi
            requests:
              cpu: 200m
              memory: 600Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: apicurio-registry-mt-ui
  name: apicurio-registry-mt-ui
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: apicurio-registry-mt-ui
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apicurio-registry-mt-ui
  labels:
    app: apicurio-registry-mt-ui
    template: apicurio-registry-mt-ui
spec:
  to:
    kind: Service
    #HEY workaround here!! because of using nameSuffix: -mt
    name: apicurio-registry-mt-ui-mt
    weight: 100
  wildcardPolicy: None