apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    application: keycloak
  name: keycloak
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    deploymentConfig: keycloak

---

apiVersion: route.openshift.io/v1
id: keycloak
kind: Route
metadata:
  annotations:
    description: Route for application's service.
  labels:
    application: keycloak
  name: keycloak
spec:
  host: ""
  tls:
    termination: edge
  to:
    name: keycloak

---

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    application: keycloak
  name: keycloak
spec:
  replicas: 2
  selector:
    deploymentConfig: keycloak
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        application: keycloak
        deploymentConfig: keycloak
      name: keycloak
    spec:
      containers:
      - args:
        - start
        env:
        # https://www.keycloak.org/server/all-config
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        - name: KC_PROXY
          value: edge
        - name: KC_HOSTNAME_STRICT
          value: 'false'
        - name: KC_PROXY
          value: edge
        - name: KC_LOG_LEVEL
          value: DEBUG

        # Custom Env Variables
        - name: KEYCLOAK_DATABASE
          valueFrom:
            secretKeyRef:
              name: rds-keycloak-credentials
              key: database
        - name: KEYCLOAK_DATASOURCE_PORT
          valueFrom:
            secretKeyRef:
              name: rds-keycloak-credentials
              key: port
        - name: KEYCLOAK_DATASOURCE_HOST
          valueFrom:
            secretKeyRef:
              name: rds-keycloak-credentials
              key: host

        # Datsource Configurations
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: "jdbc:postgresql://${KEYCLOAK_DATASOURCE_HOST}:${KEYCLOAK_DATASOURCE_PORT}/${KEYCLOAK_DATABASE}"
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: rds-keycloak-credentials
              key: user
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-keycloak-credentials
              key: password
        - name: KC_TRANSACTION_XA_ENABLED
          value: 'true'
        image: quay.io/keycloak/keycloak:21.1.1
        livenessProbe:
          failureThreshold: 100
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
        name: keycloak
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 300
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange

