apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apicurio-api-designer-ui
    component: apicurio-api-designer-ui
  name: apicurio-api-designer-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      component: apicurio-api-designer-ui
  template:
    metadata:
      labels:
        app: apicurio-api-designer-ui
        component: apicurio-api-designer-ui
    spec:
      containers:
      - image: quay.io/apicurio/apicurio-api-designer-ui:latest-snapshot
        name: apicurio-api-designer-ui
        ports:
          - name: web
            containerPort: 8080
            protocol: TCP
        env:
          - name: DESIGNER_API_URL
            value: https://apicurio-api-designer-api-rhaf-apicurio-designer.apps.dev-eng-ocp4-mas.dev.3sca.net/apis/designer/v0
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 250Mi
        livenessProbe:
          httpGet:
            path: /config.js
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /config.js
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
