apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: apicurio-api-designer
    component: apicurio-api-designer
  name: apicurio-api-designer
spec:
  replicas: 1
  selector:
    component: apicurio-api-designer
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        component: apicurio-api-designer
      name: apicurio-api-designer
    spec:
      containers:
      - image: apicurio-api-designer:latest
        imagePullPolicy: Always
        name: apicurio-api-designer
        ports:
          - name: web
            containerPort: 8080
            protocol: TCP
        env:
          - name: DESIGNER_LOG_LEVEL
            value: DEBUG
          - name: DESIGNER_ACCESS_LOG_ENABLE
            value: "true"
          - name: QUARKUS_PROFILE
            value: prod
          - name: DESIGNER_API_URL
            value: /apis/designer/v0
        resources:
          limits:
            cpu: 300m
            memory: 1300Mi
          requests:
            cpu: 100m
            memory: 600Mi
        livenessProbe:
          httpGet:
            path: /apis/designer/v0/system/info
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /apis/designer/v0/system/info
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        terminationMessagePath: /dev/termination-log
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - apicurio-api-designer
      from:
        kind: ImageStreamTag
        name: apicurio-api-designer:latest
    type: ImageChange
