apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: apicurio-api-designer-api
    component: apicurio-api-designer-api
  name: apicurio-api-designer-api
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/apicurio/apicurio-api-designer-mem:latest-snapshot
    importPolicy:
      scheduled: true
    name: latest

---

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: apicurio-api-designer-ui
    component: apicurio-api-designer-ui
  name: apicurio-api-designer-ui
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/apicurio/apicurio-api-designer-ui:latest-snapshot
    importPolicy:
      scheduled: true
    name: latest