apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: apicurio-api-designer
    component: registry
  name: apicurio-api-designer
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/apicurio/apicurio-api-designer-mem:latest-snapshot
    importPolicy:
      scheduled: true
    name: latest