apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-api.yaml
  - service-api.yaml
  - route-api.yaml
  - deployment-ui.yaml
  - service-ui.yaml
  - route-ui.yaml
