apiVersion: v1
kind: Service
metadata:
  labels:
    app: backstage
    template: backstage
  name: backstage
spec:
  selector:
    app: backstage
  ports:
    - name: app
      port: 7007
      protocol: TCP
      targetPort: 'app'
  sessionAffinity: None
status:
  loadBalancer: {}
