---
apiVersion: v1
kind: Pod
metadata:
  name: pg-client
  labels: 
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/instance: postgresql-ha
    app.kubernetes.io/component: pg-client
spec:
  containers:
    - image: bitnami/postgresql:12.15.0-debian-11-r72
      name: postgresql
      env:
      - name: ALLOW_EMPTY_PASSWORD
        value: "yes"
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi