apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: apicurio-registry-postgresql
  name: apicurio-registry-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
