- op: add
  path: "/spec/template/spec/containers/-"
  value: 
    name: envoy
    image: envoyproxy/envoy:v1.16.0
    command: ["envoy"]
    args: ["-c", "/etc/envoy.yaml", "--service-node", "apicurio", "--service-cluster", "apicurio", "-l", "debug"]
    ports:
      - name: envoy-http
        containerPort: 38080
        protocol: TCP
      - name: envoy-metrics
        containerPort: 9901
        protocol: TCP
    resources:
      limits:
        cpu: 1000m
        memory: 1300Mi
      requests:
        cpu: 200m
        memory: 600Mi
    volumeMounts:
    - name: apicurio-envoy-config
      mountPath: /etc/envoy.yaml
      subPath: envoy.yaml
- op: add
  path: /spec/template/spec/volumes
  value: 
    volumes:
      - name: apicurio-envoy-config
        configMap:
          name: apicurio-envoy-config
