apiVersion: v1
kind: ConfigMap
metadata:
  name: limitador-config
  labels:
    app: limitador
data:
  limits.yaml: |
    ---
    -
      namespace: test_namespace
      max_value: 10
      seconds: 60
      conditions:
        - "req.method == GET"
      variables:
        - user_id
    -
      namespace: test_namespace
      max_value: 5
      seconds: 60
      conditions:
        - "req.method == POST"
      variables:
        - user_id