apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ads-ui
spec:
  host: ads-ui.apps.smaug.na.operate-first.cloud

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: api-designer-poc
spec:
  host: api-designer-poc.apps.smaug.na.operate-first.cloud

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: studio-editors
spec:
  host: studio-editors.apps.smaug.na.operate-first.cloud
