apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/ads-ui
  - ../../base/api-designer-poc
  - ../../base/studio-editors
  - ../../base/apicurio-registy-mem

resources:
  - secret.yaml

patches:
  - lifecycle-hooks.yaml
