apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: apicurio-registry
    component: apicurio-registry
  name: apicurio-registry
spec:
  replicas: 1
  selector:
    component: apicurio-registry
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        component: apicurio-registry
      name: apicurio-registry
    spec:
      containers:
      - image: apicurio-registry:latest
        imagePullPolicy: Always
        name: apicurio-registry
        ports:
          - name: web
            containerPort: 8080
            protocol: TCP
        env:
          # enable authentication
          - name: AUTH_ENABLED
            value: "true"
          - name: KEYCLOAK_URL
            value: "https://keycloak-rhaf-apicurio-designer.apps.dev-eng-ocp4-mas.dev.3sca.net/"
          - name: KEYCLOAK_REALM
            value: "registry"
          - name: KEYCLOAK_API_CLIENT_ID
            value: "registry-api"
          - name: KEYCLOAK_UI_CLIENT_ID
            value: "apicurio-registry"
          
          - name: REGISTRY_ENABLE_MULTITENANCY
            value: "false"
          - name: REGISTRY_LOG_LEVEL
            value: DEBUG
          - name: LOG_LEVEL
            value: DEBUG
          - name: QUARKUS_PROFILE
            value: prod
          - name: REGISTRY_CONFIG_CACHE_ENABLED
            value: "true"
          - name: CORS_ALLOWED_ORIGINS
            value: "*"

         # Datsource Configurations
          - name: REGISTRY_DATABASE
            valueFrom:
              secretKeyRef:
                name: rds-apicurio-credentials
                key: database
          - name: REGISTRY_DATASOURCE_PORT
            valueFrom:
              secretKeyRef:
                name: rds-apicurio-credentials
                key: port
          - name: REGISTRY_DATASOURCE_HOST
            valueFrom:
              secretKeyRef:
                name: rds-apicurio-credentials
                key: host
          - name: REGISTRY_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: rds-apicurio-credentials
                key: user
          - name: REGISTRY_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rds-apicurio-credentials
                key: password
          - name: REGISTRY_DATASOURCE_URL
            value: "jdbc:postgresql://${REGISTRY_DATASOURCE_HOST}:${REGISTRY_DATASOURCE_PORT}/${REGISTRY_DATABASE}"
        resources:
          limits:
            cpu: 300m
            memory: 1300Mi
          requests:
            cpu: 100m
            memory: 600Mi
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        terminationMessagePath: /dev/termination-log
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - apicurio-registry
      from:
        kind: ImageStreamTag
        name: apicurio-registry:latest
    type: ImageChange
