apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: apicurio-registry
    component: registry-api
  name: apicurio-registry-api
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/apicurio/apicurio-registry-sql:latest-snapshot
    importPolicy:
      scheduled: true
    name: latest

---

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: apicurio-registry
    component: registry-ui
  name: apicurio-registry-ui
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/apicurio/apicurio-registry-ui:latest-snapshot
    importPolicy:
      scheduled: true
    name: latest
