apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: api-designer
    component: api-designer-poc
  name: api-designer-poc
spec:
  replicas: 1
  selector:
    component: api-designer-poc
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        component: api-designer-poc
      name: api-designer-poc
    spec:
      containers:
      - env:
        - name: AUTH_ENABLED
          value: "false"
        - name: ADS_UI_URL
          value: http://ads-ui.apps.smaug.na.operate-first.cloud/ads.js
        - name: SRS_API_URL
          value: operate-first-mock
        - name: EDITORS_URL
          value: http://studio-editors.apps.smaug.na.operate-first.cloud
        image: api-designer-poc:latest
        imagePullPolicy: Always
        name: api-designer-poc
        ports:
        - containerPort: 8080
          protocol: TCP
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - api-designer-poc
      from:
        kind: ImageStreamTag
        name: api-designer-poc:latest
    type: ImageChange