apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: api-designer
    component: api-designer-poc
  name: api-designer-poc
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/apicurio/api-designer-poc:latest-snapshot
    importPolicy:
      scheduled: true
    name: latest