apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: api-designer
    component: api-designer-poc
  name: api-designer-poc
spec:
  host: api-designer-poc.apps.smaug.na.operate-first.cloud
  port:
    targetPort: 8080-http
  to:
    kind: Service
    name: api-designer-poc
    weight: 100
  wildcardPolicy: None