apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
   - ../../base/  # Registry in-memory deployment
   - rds-external-secrets.yaml # RDS Credentials

components:
  - ../../../common-component/backstage