apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/ # Designer in-memory deployment

components:
- ../../../common-component/sso
- ../../../common-component/ha-database
