apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: apicurio-api-designer
spec:
  template:
    spec:
      containers:
      - name: apicurio-api-designer
        env:
        - name: DESIGNER_LOG_LEVEL
          value: DEBUG
        - name: DESIGNER_ACCESS_LOG_ENABLE
          value: "true"
        - name: QUARKUS_PROFILE
          value: prod
