---

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: apicurio-api-designer
spec:
  template:
    spec:
      containers:
      - name: apicurio-api-designer
        resources:
          requests:
            cpu: 300m
            memory: 1000Mi
          limits:
            memory: 1000Mi

