---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-ha
  labels:
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/instance: postgresql-ha
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - name: "postgresql"
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/instance: postgresql-ha
    app.kubernetes.io/component: postgresql
