apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: api-designer
    component: apicurio-registry-mem
  name: apicurio-registry-mem
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/apicurio/apicurio-registry-mem:latest-release
    importPolicy:
      scheduled: true
    name: latest