apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: api-designer
    component: apicurio-registry-mem
  name: apicurio-registry-mem-one
spec:
  host: ''
  port:
    targetPort: 8080-http
  to:
    kind: Service
    name: apicurio-registry-mem-one
    weight: 100
  wildcardPolicy: None

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: api-designer
    component: apicurio-registry-mem
  name: apicurio-registry-mem-two
spec:
  host: ''
  port:
    targetPort: 8080-http
  to:
    kind: Service
    name: apicurio-registry-mem-two
    weight: 100
  wildcardPolicy: None