apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: api-designer
    component: apicurio-registry-mem
  name: apicurio-registry-mem-1
spec:
  host: apicurio-registry-mem-1.apps.smaug.na.operate-first.cloud
  port:
    targetPort: 8080-http
  to:
    kind: Service
    name: apicurio-registry-mem-1
    weight: 100
  wildcardPolicy: None