apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: e2e-registry-ext-secret
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: e2e-registry-secret
  dataFrom:
   - extract:
      key: moc/smaug/apicurio-apicurio-registry/e2e-registry-secret
