apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
##FYI kustomize bug that breaks StatefulSet when setting commonLabels
##https://github.com/kubernetes-sigs/kustomize/issues/504
# commonLabels:
#   app.kubernetes.io/name: keycloak-apicurio
resources:
  - keycloak-server.yaml
  - postgres-keycloak.yaml
