# Routes
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apicurio-registry
  labels:
    app: apicurio-registry
    template: apicurio-registry
spec:
  to:
    kind: Service
    name: apicurio-registry
    weight: 100
  wildcardPolicy: None
