kind: ConfigMap
apiVersion: v1
metadata:
  name: registry-deployments-config-file
  labels:
    app: fleet-manager
data:
  registry-deployments.yaml: |-
    deployments:
      - name: default
        # Route to registry
        registryDeploymentUrl: https://apicurio-registry-mt-apicurio-apicurio-registry.apps.smaug.na.operate-first.cloud/
        # Path to tenant manager service
        tenantManagerUrl: http://tenant-manager-mt:8585 
