apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:  
  # - ../base  # normal deployment  
  - ../../overlay/multitenancy # multitenancy deployment

components:
  - ../../component/backstage
  - ../../component/housekeeping