apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: api-designer
    component: ads-ui
  name: ads-ui
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/apicurio/api-designer-ads:latest-snapshot
    importPolicy:
      scheduled: true
    name: latest