name: Deploy Latest Designer Docker Images (3scale-dev)

on:
  workflow_dispatch:

jobs:

  deploy-latest-designer:
    name: Deploy Latest Designer Image
    runs-on: ubuntu-latest
    if: github.repository_owner == 'apicurio'
    env:
      API_IMAGE: quay.io/apicurio/apicurio-designer-mem
      UI_IMAGE: quay.io/apicurio/apicurio-designer-ui
      IMAGE_TAG: latest-snapshot
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get digest (API)
        run: |
          docker pull ${{ env.API_IMAGE }}:${{ env.IMAGE_TAG }}
          docker image inspect ${{ env.API_IMAGE }}:${{ env.IMAGE_TAG }}
          DESIGNER_API_DOCKER_IMAGE=$(docker image inspect --format='{{index .RepoDigests 0}}' ${{ env.API_IMAGE }}:${{ env.IMAGE_TAG }})
          echo "DESIGNER_API_DOCKER_IMAGE=$DESIGNER_API_DOCKER_IMAGE" >> $GITHUB_ENV

      - name: Get digest (UI)
        run: |
          docker pull ${{ env.UI_IMAGE }}:${{ env.IMAGE_TAG }}
          docker image inspect ${{ env.UI_IMAGE }}:${{ env.IMAGE_TAG }}
          DESIGNER_UI_DOCKER_IMAGE=$(docker image inspect --format='{{index .RepoDigests 0}}' ${{ env.UI_IMAGE }}:${{ env.IMAGE_TAG }})
          echo "DESIGNER_UI_DOCKER_IMAGE=$DESIGNER_UI_DOCKER_IMAGE" >> $GITHUB_ENV

      - name: Echo the Docker Images
        run: |
          echo "API image: $DESIGNER_API_DOCKER_IMAGE"
          echo " UI image: $DESIGNER_UI_DOCKER_IMAGE"

      - name: Code Checkout
        run: |
          mkdir repo
          cd repo
          git init
          git config --global user.name "apicurio-ci"
          git config --global user.email "apicurio.ci@gmail.com"
          git remote add origin "https://apicurio-ci:${{ secrets.ACCESS_TOKEN }}@github.com/Apicurio/apicurio-operate-first.git"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull

      - name: Update API Docker Image
        run: |
          npm install -g yaml-cli
          cd repo/manifests/designer/base/
          yaml set deployment-api.yaml spec.template.spec.containers.0.image ${{ env.DESIGNER_API_DOCKER_IMAGE }} > deployment-api-NEW.yaml
          rm deployment-api.yaml
          mv deployment-api-NEW.yaml deployment-api.yaml

      - name: Update UI Docker Image
        run: |
          cd repo/manifests/designer/base/
          yaml set deployment-ui.yaml spec.template.spec.containers.0.image ${{ env.DESIGNER_UI_DOCKER_IMAGE }} > deployment-ui-NEW.yaml
          rm deployment-ui.yaml
          mv deployment-ui-NEW.yaml deployment-ui.yaml

      - name: Verify Changed Deployment
        run: |
          cd repo
          echo "---"
          cat manifests/designer/base/deployment-api.yaml
          echo "---"
          cat manifests/designer/base/deployment-ui.yaml
          echo "---"

      - name: Commit Changes
        run: |
          cd repo
          git add .
          git commit -m 'Automatic upgrade of Designer container images.'
          git push origin main
