name: Deploy Latest Registry (3scale-dev)

on:
  workflow_dispatch:

jobs:

  deploy-latest-registry:
    name: Deploy Latest Registry Image
    runs-on: ubuntu-latest
    if: github.repository_owner == 'apicurio'
    steps:
      - name: Get digest (API)
        run: |
          docker pull quay.io/apicurio/apicurio-registry-sql:latest-snapshot
          docker image inspect quay.io/apicurio/apicurio-registry-sql:latest-snapshot
          REGISTRY_API_DOCKER_IMAGE=$(docker image inspect --format='{{index .RepoDigests 0}}' quay.io/apicurio/apicurio-registry-sql:latest-snapshot)
          echo "REGISTRY_API_DOCKER_IMAGE=$REGISTRY_API_DOCKER_IMAGE" >> $GITHUB_ENV

      - name: Get digest (UI)
        run: |
          docker pull quay.io/apicurio/apicurio-registry-ui:latest-snapshot
          docker image inspect quay.io/apicurio/apicurio-registry-ui:latest-snapshot
          REGISTRY_UI_DOCKER_IMAGE=$(docker image inspect --format='{{index .RepoDigests 0}}' quay.io/apicurio/apicurio-registry-ui:latest-snapshot)
          echo "REGISTRY_UI_DOCKER_IMAGE=$REGISTRY_UI_DOCKER_IMAGE" >> $GITHUB_ENV

      - name: Echo the Docker Images
        run: |
          echo "API image: $REGISTRY_API_DOCKER_IMAGE"
          echo " UI image: $REGISTRY_UI_DOCKER_IMAGE"

      - name: Code Checkout
        run: |
          mkdir repo
          cd repo
          git init
          git config --global user.name "apicurio-ci"
          git config --global user.email "apicurio.ci@gmail.com"
          git remote add origin "https://apicurio-ci:${{ secrets.ACCESS_TOKEN }}@github.com/Apicurio/apicurio-operate-first.git"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull

      - name: Update API Docker Image
        uses: fjogeleit/yaml-update-action@v0.9.0
        with:
          valueFile: 'repo/manifests/registry/base/deployment-api.yaml'
          propertyPath: 'spec.template.spec.containers[:1].image'
          value: ${{ env.REGISTRY_API_DOCKER_IMAGE }}
          commitChange: false

      - name: Update UI Docker Image
        uses: fjogeleit/yaml-update-action@v0.9.0
        with:
          valueFile: 'repo/manifests/registry/base/deployment-ui.yaml'
          propertyPath: 'spec.template.spec.containers[:1].image'
          value: ${{ env.REGISTRY_UI_DOCKER_IMAGE }}
          commitChange: false

      - name: Cat Changed Deployment
        run: |
          cd repo
          echo "---"
          cat manifests/registry/base/deployment-api.yaml
          echo "---"
          cat manifests/registry/base/deployment-ui.yaml
          echo "---"
          git status
