apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#commonLabels:
#  app.kubernetes.io/name: apicurio
resources:
  - deployment-config.yaml
  - service.yaml
  - route.yaml
  - image-stream.yaml
